copy  "C:\multifacturas_sdk\instaladores windows\windows\64bits\xlstproc\system32" C:\WINDOWS\system32
copy  "C:\multifacturas_sdk\instaladores windows\windows\64bits\xlstproc\system64" C:\WINDOWS\system64
"C:\multifacturas_sdk\instaladores windows\windows\64bits\openssl\vcredist_x64.exe"
"C:\multifacturas_sdk\instaladores windows\windows\64bits\openssl\Win64OpenSSL_Light-1_0_1e.exe"

CP C:\OpenSSL-Win64\*  C:\WINDOWS\
CP C:\OpenSSL-Win64\bin\*  C:\WINDOWS\






